=== eshumovich/lawyer-office-maven-new/src/main/resources/lawyerOffice.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="lawyerOffice">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="lawyers">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="lawyer" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="address">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="country"/>
                                                    <xs:element type="xs:string" name="city"/>
                                                    <xs:element type="xs:short" name="houseNumber"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element type="xs:string" name="birthday"/>
                                        <xs:element type="xs:byte" name="rating"/>
                                        <xs:element type="xs:short" name="salary"/>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="name" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="services">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="service" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="descriptionOfService"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="clients">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="client" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="clientCase">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="description"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element type="xs:short" name="money"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== eshumovich/lawyer-office-maven-new/src/main/resources/lawyerOffice.xml
<?xml version="1.0" encoding="UTF-8"?>

<lawyerOffice name="REDCLEARING" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="lawyerOffice.xsd">
    <lawyers>
        <lawyer name="Rachel Green">
            <address>
                <country>France</country>
                <city>Paris</city>
                <houseNumber>12</houseNumber>
            </address>
            <birthday>1990-10-12</birthday>
            <rating>7</rating>
            <salary>1100</salary>
        </lawyer>
        <lawyer name="Monica Geller">
            <address>
                <country>UK</country>
                <city>London</city>
                <houseNumber>101</houseNumber>
            </address>
            <birthday>1986-12-08</birthday>
            <rating>9</rating>
            <salary>1500</salary>
        </lawyer>
        <lawyer name="John">
            <address>
                <country>Belarus</country>
                <city>Brest</city>
                <houseNumber>148</houseNumber>
            </address>
            <birthday>1990-05-01</birthday>
            <rating>8</rating>
            <salary>1300</salary>
        </lawyer>
        <lawyer name="Nikita">
            <address>
                <country>Spain</country>
                <city>Porto</city>
                <houseNumber>101</houseNumber>
            </address>
            <birthday>2000-08-04</birthday>
            <rating>5</rating>
            <salary>700</salary>
        </lawyer>
    </lawyers>
    <services>
        <service>
            <descriptionOfService>Low Severity</descriptionOfService>
        </service>
        <service>
            <descriptionOfService>ASAP</descriptionOfService>
        </service>
        <service>
            <descriptionOfService>ASAP</descriptionOfService>
        </service>
    </services>
    <clients>
        <client>
            <clientCase>
                <description>Divorce process</description>
            </clientCase>
            <money>1500</money>
        </client>
        <client>
            <clientCase>
                <description>Aliments</description>
            </clientCase>
            <money>1350</money>
        </client>
    </clients>
</lawyerOffice>
